// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcLUJVZj_o3x4m60z3qqxHNiOidIO3T58',
    appId: '1:185464546163:web:486641b1060ecddc25db06',
    messagingSenderId: '185464546163',
    projectId: 'my-medicine-5cac9',
    authDomain: 'my-medicine-5cac9.firebaseapp.com',
    storageBucket: 'my-medicine-5cac9.firebasestorage.app',
    measurementId: 'G-FMWKMP5M2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRX4RBuYRY7n2EQFB56kLjBlEl2teU3hE',
    appId: '1:185464546163:android:5be0b818b4bda2ba25db06',
    messagingSenderId: '185464546163',
    projectId: 'my-medicine-5cac9',
    storageBucket: 'my-medicine-5cac9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEpkDMzO5STcsWE8W6ee6Q9VtyYKC5KnY',
    appId: '1:185464546163:ios:73a69daefb2a978a25db06',
    messagingSenderId: '185464546163',
    projectId: 'my-medicine-5cac9',
    storageBucket: 'my-medicine-5cac9.firebasestorage.app',
    iosBundleId: 'com.example.myMedicine',
  );
}
